---
title: "mnist"
author: "Chen Ning Kuan"
date: "2020年3月31日"
output: 
  html_document:
    theme: cerulean
    toc: true
    # toc_depth: 2
    number_sections: true
  # word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load data

there are two way to read data one is load in your computer.one is load on github

- when you read data in your computer you can use getwd( ) and put the data and this rmd file in the same folder then you can read data very easy like my example

```{r}
require(magrittr)
require(readr)
getwd()
train <- read_csv('train.csv')
```
-when you use github to read data you must add raw after http://

```{r}
require(readr)
train <- read_csv("https://raw.githubusercontent.com/empireisme/machine-learning-and-econometrics/master/train.csv")
```


```{r}

class(train)
obs.matrix <- matrix(unlist(train[1, -1]), # ignore 'label'
                     nrow = 28,            
                     byrow=T)
str(obs.matrix)

image(obs.matrix, 
      col=grey.colors(255))


rotate <- function(matrix){
  t(apply(matrix, 2, rev)) 
} 

obs.matrix<- matrix(train[1, -1],nrow = 28,byrow = T)
class(obs.matrix   )

par(mfrow=c(2,4))
for(x in 1:8){
  obs.matrix <- matrix(unlist(train[x, -1]), # ignore 'label'
                              nrow = 28,            
                              byrow=T)
         
  image(rotate(obs.matrix),
               col=grey.colors(255),
               xlab=paste("Label", train[x, 1], sep=": "),
               cex.lab = 1.5
       )
}

```

```{r}
x <- stats::runif(12); y <- stats::rnorm(12)
i <- order(x, y); x <- x[i]; y <- y[i]
plot(x,y, main = "arrows(.) and segments(.)")
s <- seq(length(x)-1)  # one shorter than data
arrows(x[s], y[s], x[s+1], y[s+1], col = 1:3)
```

